// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onXPositionChange();
void onYPositionChange();
void onAlarmChange();
void onMotionDetectChange();
void onResetChange();
void onWaterPumpChange();

float waterLevel;
float xPosition;
float yPosition;
bool alarm;
bool motionDetect;
bool reset;
bool waterPump;

void initProperties(){

  ArduinoCloud.addProperty(waterLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(xPosition, READWRITE, ON_CHANGE, onXPositionChange);
  ArduinoCloud.addProperty(yPosition, READWRITE, ON_CHANGE, onYPositionChange);
  ArduinoCloud.addProperty(alarm, READWRITE, ON_CHANGE, onAlarmChange);
  ArduinoCloud.addProperty(motionDetect, READWRITE, ON_CHANGE, onMotionDetectChange);
  ArduinoCloud.addProperty(reset, READWRITE, ON_CHANGE, onResetChange);
  ArduinoCloud.addProperty(waterPump, READWRITE, ON_CHANGE, onWaterPumpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
